
all:

clean:
	rm -f LocalSessionLog.txt
	rm -f *.mexmaci64
	rm -f gui_state.mat
	rm -f model_gui_log.txt
	rm -f system_help_reserved_words.txt
	rm -rf pdm_gui_log.txt
	rm -f transient/*
	rmdir transient

